title: Cloud computing experiment
page-top-title: Yourname
top-section-bg-text: Be what you want to be
home-subtitle: personal website
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
