title: Cloud computing experiment
page-top-title: Yourname
top-section-bg-text: Be what you want to be
home-subtitle: personal website
copyright-text: 'personal-homepage-gs-2025/3/12.'
blog-path: /contents/blog   # 添加博客路径配置